package HealthCareInterfaceApp;


/**
* HealthCareInterfaceApp/HealthCareInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Health_Management_Interface.idl
* Tuesday, 27 February, 2024 1:07:54 PM EST
*/

public interface HealthCareInterface extends HealthCareInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HealthCareInterface
