package HealthCareInterfaceApp;


/**
* HealthCareInterfaceApp/HealthCareInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Health_Management_Interface.idl
* Tuesday, 27 February, 2024 1:07:54 PM EST
*/

public interface HealthCareInterfaceOperations 
{

  // Define addAppointment method
  String addAppointment (String appointmentID, String appointmentType, int capacity);

  // Define removeAppointment method
  String removeAppointment (String appointmentID, String appointmentType);

  // Define listAppointmentAvailabilty method
  String listAppointmentAvailability (String appointmentType);

  // Define bookAppointment method
  String bookAppointment (String patientID, String appointmentID, String appointmentType);

  // Define getAppointmentSchedule method
  String getAppointmentSchedule (String patientID);

  // Define cancelAppointment method
  String cancelAppointment (String patientID, String appointmentID);

  // Define swap Appointment method
  String swapAppointment (String patientID, String newAppointmentID, String newAppointmentType, String oldAppointmentID, String oldAppointmentType);
  void shutdown ();
} // interface HealthCareInterfaceOperations
