package HealthCareInterfaceApp;

/**
* HealthCareInterfaceApp/HealthCareInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Health_Management_Interface.idl
* Tuesday, 27 February, 2024 1:07:54 PM EST
*/

public final class HealthCareInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public HealthCareInterfaceApp.HealthCareInterface value = null;

  public HealthCareInterfaceHolder ()
  {
  }

  public HealthCareInterfaceHolder (HealthCareInterfaceApp.HealthCareInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HealthCareInterfaceApp.HealthCareInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HealthCareInterfaceApp.HealthCareInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HealthCareInterfaceApp.HealthCareInterfaceHelper.type ();
  }

}
